# Spring Boot configuration
spring:
  profiles:
    active: development
#  # Security configuration
  security:
    user:
      name: admin
      password: admin
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BIG_DATA_WEB?serverTimezone=UTC&pinGlobalTxToPhysicalConnection=true
    username: root
    password: bhbyf.hnftdf
    xa:
      data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
    servlet:
      content-type: text/html

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: error
    org.hibernate: trace
# Server configuration

server:
  port: 8080 #set your port



